# 微服务建议一定要写服务端口号和微服务名称
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  #采样率值介于0到1之间，1则表示全部采集（一般为0.5就够了）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.178.141.179:3306/db2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: LvHA#2k^yw3


eureka:
  client:
    # 表示向注册中心注册自己，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
      # defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true   #访问路径可以显示ip地址

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.cn.edu.springcloud.entities # 所有entities别名类所在包